$(function(){
	plumeLog("进入brandList模板自定义js-"+plumeTime());
	$(".btn-addbrand").bind("click",function(){
		$(".work-space-active").html("").loadTemp("brandAdd","nochangeurl",function(){
			$(".ba-back").bind("click",function(){
				$(".work-space-active").html("").loadTemp("brandList","nochangeurl");
			})
		});
	});
})